CREATE TABLE
	"ESTADOS" (
		"UF_ID" NUMBER NOT NULL ENABLE,
		"UF" VARCHAR2 (2),
		"NOME" VARCHAR2 (30),
		"LATITUDE" NUMBER (10, 6),
		"LONGITUDE" NUMBER (10, 6),
		"REGIAO" VARCHAR2 (20),
		CONSTRAINT "ESTADOS_PK" PRIMARY KEY ("UF_ID") USING INDEX ENABLE
	);

	