CREATE TABLE
	"MUNICIPIOS" (
		"MUNICIPIO_ID" NUMBER NOT NULL ENABLE,
		"CODIGO_IBGE" NUMBER NOT NULL ENABLE,
		"NOME" VARCHAR2 (100) NOT NULL ENABLE,
		"LATITUDE" NUMBER (10, 6) NOT NULL ENABLE,
		"LONGITUDE" NUMBER (10, 6) NOT NULL ENABLE,
		"CAPITAL" NUMBER DEFAULT 0 NOT NULL ENABLE,
		"UF_ID" NUMBER NOT NULL ENABLE,
		"SIAFI_ID" VARCHAR2 (4) NOT NULL ENABLE,
		"DDD" NUMBER NOT NULL ENABLE,
		"FUSO_HORARIO" VARCHAR2 (32) NOT NULL ENABLE,
		CONSTRAINT "MUNICIPIOS_PK" PRIMARY KEY ("MUNICIPIO_ID") USING INDEX ENABLE
	);

ALTER TABLE "MUNICIPIOS" ADD CONSTRAINT "MUNICIPIOS_FK" FOREIGN KEY ("UF_ID") REFERENCES "ESTADOS" ("UF_ID") ON DELETE SET NULL ENABLE;